version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10.13.0
        steps:
            - checkout
            - run: npm install
            - run: npm run test:unit -- --reporter mocha-junit-reporter --reporter-options mochaFile=./tests/unit/test-results/mocha/unit-tests-results.xml
            - store_test_results:
                path: ./tests/unit/test-results
